{
  "version": 1,
  "status": "fail",
  "message": "\u001b[01;32m\u001b[KExamplePartialFailSpec > Year not divisible by 4 in common year PASSED\u001b[m\u001b[K\n\n\u001b[01;32m\u001b[KExamplePartialFailSpec > Year divisible by 2, not divisible by 4 in common year PASSED\u001b[m\u001b[K\n\n\u001b[01;32m\u001b[KExamplePartialFailSpec > Year divisible by 4, not divisible by 100 in leap year PASSED\u001b[m\u001b[K\n\n\u001b[01;32m\u001b[KExamplePartialFailSpec > Year divisible by 100, not divisible by 400 in common year PASSED\u001b[m\u001b[K\n\n\u001b[01;32m\u001b[KExamplePartialFailSpec > Year divisible by 100 but not by 3 is still not a leap year PASSED\u001b[m\u001b[K\n\n\u001b[01;31m\u001b[KExamplePartialFailSpec > Year divisible by 400 in leap year FAILED\u001b[m\u001b[K\n    Condition not satisfied:\n\n    new ExamplePartialFail(year).isLeapYear() == expected\n    |                      |     |            |  |\n    |                      2000  false        |  true\n    <ExamplePartialFail year=2000>   false\n        at ExamplePartialFailSpec.Year divisible by 400 in leap year(ExamplePartialFailSpec.groovy:58)\n\n6 tests completed, 1 failed\n\n\u001b[01;31m\u001b[KFAILURE: Build failed with an exception.\u001b[m\u001b[K\n\n* What went wrong:\nExecution failed for task ':test'.\n> There were failing tests. "
}
